[package]
name = "sc2k-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"