[package]
name = "sc2k-lib"
version = "0.2.0"
edition = "2021"

[lib]
name = "sc2klib"
path = "src/sc2klib/mod.rs"

[[bin]]
name = "sc2kcli"
path = "src/cli.rs"

[dependencies]
byteorder = "1.5.0"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
